version: '3'
services:
  solr:
    image: solr:9.8.0
    container_name: solr-catalog
    ports:
      - "8983:8983"
    volumes:
      - ./configsets:/configsets
      - solr_data:/var/solr
      - ./cell_phone_catalog_expanded.csv:/data/cell_phone_catalog_expanded.csv
    environment:
      - SOLR_HEAP=512m
    command:
      - solr-precreate
      - catalog
      - /configsets/catalog/conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/info/system"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  solr_data:
